// Shared slug utilities used by both /functions/image/[slug].js and
// /functions/sitemap.xml.js.
//
// IMPORTANT: the same logic (slugify + assignSlugs) also lives, byte-for-byte,
// inside the client-side <script> in index.html, so gallery card links
// resolve to the exact same slug the server hands out. If you ever change
// the algorithm here, update index.html to match — otherwise old links
// generated by one side will 404 on the other.

export function slugify(text) {

    return String(text || "")
        .toLowerCase()
        .normalize("NFKD")
        .replace(/[\u0300-\u036f]/g, "")
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/^-+|-+$/g, "")
        .replace(/-{2,}/g, "-");

}

// Deterministically turns a list of {id, title} rows (must be sorted by
// id ascending) into unique slugs. The first image to produce a given
// base slug keeps it clean (e.g. "cpu-socket"); any later image whose
// title slugifies to the same thing gets "-<id>" appended so URLs never
// collide.

export function assignSlugs(rows) {

    const seen = new Set();
    const idToSlug = new Map();
    const slugToId = new Map();

    rows.forEach(function (row) {

        let slug = slugify(row.title) || ("image-" + row.id);

        if (seen.has(slug)) {
            slug = slug + "-" + row.id;
        }

        seen.add(slug);
        idToSlug.set(row.id, slug);
        slugToId.set(slug, row.id);

    });

    return { idToSlug, slugToId };

}
